DROP TABLE IF EXISTS trip CASCADE;
DROP TABLE IF EXISTS todo CASCADE;

CREATE TABLE trip(
  id SERIAL PRIMARY KEY NOT NULL,
  date date NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  city_id INT REFERENCES cities(id) ON DELETE CASCADE
);

CREATE TABLE todo(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  trip_id INT REFERENCES trip(id) ON DELETE CASCADE
)


